### PR TITLE
Streams in Artery

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by drewhk** [comment]
Hm, shouldn't we have an overview post that highlights interesting features like buffer pools, compression, caching using specialized hashmaps, writing/reading from DirectBuffers the protocol format, etc.

**Comment by patriknw** [comment]
I think this gives enough overview and then we will publish more posts that describe things in more detail. Overview of these internal implementation details without actually explaining them doesn't have much value in my opinion.

**Comment by drewhk** [comment]
It depends what is the goal of this series. I thought we want a deep dive into internals in the series, showing off various interesting tricks.

**Comment by patriknw** [comment]
yes, that is my intention. I wrote "so in the blog we will take a look under the hood and describe how we implemented some of it. In this first post I will show an overview of how we have used Akka Streams in Artery."

**Comment by drewhk** [comment]
Ah, Ok, I though that you enumerate the things we will show in the first post.

**Comment by patriknw** [comment]
alright, is it that bad, or have you not read it?

**Comment by drewhk** [comment]
No, it is not bad at all, I just felt it a bit *in medias res* with immediately starting with one aspect (using streams) and not have a lead-in post outlining areas we will cover, but probably not that important anyway (the posts in a track will be listed anyway).

**Comment by patriknw** [comment]
and I don't know exactly what we will write about, and especially don't want to promise too much, given that it was over a month since we posted something here last time

**Comment by drewhk** [comment]
Ok, fair enough.

**Pull request merged**
