### PR TITLE
Crazy JS to include author snippets

### PR DESCRIPTION
**Pull request by ktoso**
Before:
mastering_graphstages__part_1__introduction____akka_team_blog

After: 
mastering_graphstages__part_1__introduction____akka_team_blog

### CODE REVIEW

**Comment by johanandren** [comment]
👍

**Comment by drewhk** [comment]
Hm, I am not sure. I don't mind I guess, but might be too much?

**Comment by ktoso** [comment]
It's not as big as it looks on the screenshots when compared to amount of text in posts I think.

WDYT @patriknw

**Comment by patriknw** [comment]
I don't have a strong opinion. I don't think it adds much value and wall of text can be an disadvantage.

**Comment by ktoso** [comment]
Not adding until we do a proper blog design then I guess

**Pull request closed without merging**
